Book-ing/Book-ing_BE

server.js

1. 운영서버 내 https 통신관련 서버코드 추가
2022. 04. 26. commit by  hsyoo

feat(https): SSL 적용

---

schemas/bannedUsers.js
schemas/chats.js
schemas/codes.js
schemas/meeting.js
schemas/meetingMember.js
schemas/studyMembers.js
schemas/studys.js
schemas/user.js

DB스키마 정의 함
2022.04.26 actual project:book-ing

bulid (shemas):DB 스키마 만들기

---

schemas/meeting.js
schemas/studys.js
schemas/user.js

autoIdsetter에 포함된 pk 스키마 정의에서 뺌
2022.04.26 actual project:book-ing

chore(dbSchemas): DB 스카마 정의 수정

---

app.js
package-lock.json
package.json
passport/index.js
passport/kakaoStrategy.js
routes/auth.js
routes/index.js
schemas/user.js

passport를 사용하여 소셜로그인 구현
2022.04.28 actual project: book-ing

fear(kakaoLogin): 카카오 소셜 로그인 구현

---

middlewares/auth-middlewares.js
middlewares/jwt.js
passport/kakaoStrategy.js
routes/auth.js
schemas/bannedUsers.js
schemas/chats.js
schemas/codes.js
schemas/meeting.js
schemas/meetingMember.js
schemas/studyMembers.js
schemas/studys.js
schemas/user.js

카카오 계정에서 프로필이나 닉네임을 수정하고 로그인했을 때 업데이트 하기
DB 스키마 redDate 오타 수정하기 ㅜㅠ
2022.04.28 actual project: book-ing

chor(dbSchema , login): DB 오타 수정 및 카카오 로그인 프로필 업데이트

---

controllers/mainController.js
lib/util.js
routes/index.js
routes/main.js

1. 메인페이지 조회기능 추가
ㄴ 모든 케이스에 따라 조회되도록 분기생성
2022. 04. 28.
commit by HSYOO.

feat(mainpage): 메인페이지 조회기능 중간 Commit

---

controllers/mainController.js

1. mainpage 작업중이던 것 중간 commit
2022. 04. 29.

feat(mainpage): mainpage 작업중이던 것 중간 commit

---

appspec.yml
controllers/mainController.js
package-lock.json
package.json
routes/auth.js

cicd 반영
2022. 04. 29.
commit by hsyoo

chore(cicd): cicd 반영

---

controllers/meetingController.js
routes/meeting.js

스키마 관련 선언을 UPPER_CASE로 수정
2022.04.29 actual project: book-ing

style(meeting): style controller for meeting

---

controllers/meetingController.js
routes/meeting.js

모임 인원들 프로필 보는 API를 추가 중입니다.
2022.04.30 실전프로젝트 book-ing

feat(meeting): add new API for meeting

---

controllers/authController.js

- authController.js 리다이렉트 URL 수정
2022. 04. 20.

chore(feature/main): authController.js 수정

---

app.js
controllers/authController.js

chore(feature/kakaologin): kakao login 수정본 반영

---

controllers/authController.js
controllers/mainController.js
lib/util.js

1. authController.js
- 기존 쿠키로 내려주던 JWT 토큰을 JSON으로 내려주는 방식으로 변경
2. mainController.js
- 해당 유저의 모임장 여부 추가
- 인기모임에서 추천모임으로 로직변경
- 모든 모임 데이터는 5개씩 내려주도록 변경
3.util 내 getDate() 함수 수정
- 기존 현재시간만 주던 기능을 현재시간에서 시간을 계산할 수 있도록 로직추가
2022. 05. 03.

chore(feature/mainpage): auth, mainController 및 util 내 getDate() 함수 수정

---

controllers/authController.js
controllers/mypageController.js
routes/index.js
routes/mypage.js

- 마이페이지 API 추가 중 및 로그인계정 생성 시 statusMessage에 빈값 추가하도록 수정
2022. 05. 04.

feat(feature/mypage): 마이페이지 API 추가 중

---

controllers/mainController.js
controllers/mypageController.js
lib/jwt.js
routes/main.js
routes/mypage.js

chore(feature/mypage) : mainController 수정, mypage 기능 추가

---

controllers/mypageController.js

- 마이페이지 6개 API 제작 완료
2022. 05. 06.

feat(featrue/mypage) : 마이페이지 모듈 API 제작

---

controllers/searchController.js
routes/index.js
routes/search.js

- 서칭페이지 검색 API 추가
2022. 05. 06.

feat(feature/searchpage): 서칭페이지 API 추가

---

lib/jwt.js
middlewares/auth-middlewares.js
routes/auth.js

chore(feature/auth) : auth-middleware, refreshToken 방식 수정

---

controllers/mainController.js

- meetingLocation, meetingCategory 한글로 내려가도록 수정
2022. 05. 09.

chore(featrure/mainpage) : location, category 한글처리

---

controllers/searchController.js

fix(chore/searchController) : 검색결과 취합 중 발생하는 오류 수정.

---

controllers/searchController.js

fix(searchController) : 클라이언트에서 받아온 값 비교 시 형변환 문제 수정

---

controllers/studyNoteController.js

스터디 일시 전 노트작성 가능하게 바꿈
2022-05-20 실전프로젝트 :Book-ing

chore(feature/study):스터디 노트 작성 api

---

socket.js

joinMeetingRoom을 하면 채팅 로그를 드리는 로직을 추가하였습니다.
2022.05.21 실전프로젝트 Book-ing

fix(chat): fix socket.js for chat

---

controllers/mypageController.js

people 를 const 로 변수 설정
2022-05-23 실전프로젝트:Book-ing

chore(feature/study): 마이페이지 내가 만든 스터디 조회

---

controllers/mypageController.js
controllers/studyController.js

콘솔 제거 및 const people 설정
2022-05-23 실전프로젝트 :Book-ing

chore(feature/study): 마이페이지 스터디조회

---

controllers/studyController.js

코드 값 받는 거 수정
2022-05-24 실전프로젝트:Book-ing

chore(feature/study): 온라인 스터디 조회 수정

---

controllers/studyController.js

스터디 수정
2022-05-24 실전프로젝트:Book-ing

chore(onOffStudy) :스터디 api 수정

---

controllers/studyController.js

스터디 검색할 때도 스터디 타입 내려주기
2022-05-25 실전프로젝트 :Book-ing

chore(onOffStudy) : 스터디 검색 api

---

controllers/studyController.js
socket.js

화상채팅으로 피어 피어들간에 비디오 연결 추가
2022-05-25 실전프로젝트:Book-ing

feat(onOffStudy) : 온라인 스터디 기능 추가

---

schemas/chats.js
socket.js

socket.js, chat 스키마 수정
2022.05.26 실전프로젝트 Book-ing

fix(socket): fix socket.js for socket

---

schemas/chats.js

chat 스키마 roomId=> meetingId로 수정
2022-05-26 실전프로젝트:Book-ing

chore(onOffStudy) : chat 스키마 수정

---

controllers/mypageController.js

마이페이지 내가 가입한 모임 조회 API를 수정하였습니다.
1. 내가 가입한 모임에 내가 만든 모임은 조회가 안되게 변경
2. 가입한 모임에 스터디가 없을 때 났던 오류를 수정
2022.05.27 실전프로젝트 Book-ing

fix(mypage): fix controller for mypage

---

app.js
logging.js
package-lock.json
package.json

로깅을 위해 winston 외 1개의 라이브러리를 추가했습니다.
app.js 를 수정했습니다.
logging.js 를 추가하였습니다.
2022.05.27 실전프로젝트 Book-ing

feat(log): add new File for log

---

controllers/studyController.js

스터디 참가/취소 API를 에러핸들러 처리가 가능하게 변경하였습니다.
종료된 스터디에 참여하지 못하게 하는 로직의 응답값을 변경하였습니다.
2022.05.30 실전프로젝트 Book-ing

refactor(study): refactor controller for study
